### ISSUE TITLE
@Yassine-Ag TODO List

### ISSUE THREAD

**Issue by MERZAK-X** [MERZAK-X/SimpleXML#2]
## @Yassine-Ag your **TODO** list here:

- [x]  Add function to test the SQL Connection
- [ ]  Test and finish the `XML2DB->export2DB()` / `XML2DB->importDB()` / `XML-GUI->Conn-DB`
(Which is just a basic display of the DB table contents to the DataGridView)
- [x]  ~Redesign the UI~ _@MERZAK-X did_
- [ ]  Handel Exceptions
- [ ]  A Database connection `Form` ~(that returns `DataSet` through a public member function)~ that opens a new XML-GUI `Form` using a new Constructor `XmlGUI(DataSet ds)`

> _Please be aware that although I tried using Windows10 with a bootable USB Drive, I wasn't able to install MS-SQL server and its components, this is why I opened #2_
